
name: load_more_wrapper
description: A stateless and reusable Flutter widget to add load-more functionality to scrollable widgets.
version: 1.0.0
homepage: https://github.com/ahmedelmwafy/load_more_wrapper
environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

executables:
  load_more_wrapper: bin/load_more_wrapper.dart


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
